SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

-- Make TenantId and BranchId nullable across all tables
-- This bypasses the EF migration FK cascade path issues

-- 1. Drop all foreign keys that reference TenantId or BranchId columns
-- (We'll recreate them after altering the columns)

-- Branches.TenantId FK
ALTER TABLE [Branches] DROP CONSTRAINT [FK_Branches_Tenants_TenantId];
-- BranchUsers.BranchId FK
ALTER TABLE [BranchUsers] DROP CONSTRAINT [FK_BranchUsers_Branches_BranchId];
-- Departments.BranchId FK
ALTER TABLE [Departments] DROP CONSTRAINT [FK_Departments_Branches_BranchId];
-- TenantUsers.TenantId FK
ALTER TABLE [TenantUsers] DROP CONSTRAINT [FK_TenantUsers_Tenants_TenantId];

-- 2. Alter TenantId columns to nullable
ALTER TABLE [Warehouses] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Wards] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Vitals] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Visits] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [TaxConfigurations] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Suppliers] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockTransfers] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockMovements] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockBatches] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Services] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [ServiceCategories] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Rooms] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Queues] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [PurchaseOrders] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Prescriptions] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Payments] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Patients] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [PatientInsurances] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [PatientDocuments] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [PatientCategories] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [NursingNotes] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Notifications] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [MedicalOrders] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Manufacturers] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Items] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [ItemCategories] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Invoices] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [InsurancePlans] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [InsuranceCompanies] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [InsuranceClaims] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [GoodsReceipts] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Floors] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [EmergencyVisits] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Departments] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [CorporateClients] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Buildings] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Branches] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Beds] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [BedAllocations] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Appointments] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Admissions] ALTER COLUMN [TenantId] UNIQUEIDENTIFIER NULL;

-- 3. Alter BranchId columns to nullable
ALTER TABLE [Warehouses] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Wards] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Vitals] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Visits] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockTransfers] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockMovements] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [StockBatches] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Rooms] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Queues] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [PurchaseOrders] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Prescriptions] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Payments] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [NursingNotes] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [MedicalOrders] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Invoices] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [InsuranceClaims] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [GoodsReceipts] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Floors] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [EmergencyVisits] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Departments] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Buildings] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Beds] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [BedAllocations] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Appointments] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;
ALTER TABLE [Admissions] ALTER COLUMN [BranchId] UNIQUEIDENTIFIER NULL;

-- 4. Recreate foreign keys with NO ACTION (safe, no cascade conflicts)
ALTER TABLE [Branches] ADD CONSTRAINT [FK_Branches_Tenants_TenantId]
    FOREIGN KEY ([TenantId]) REFERENCES [Tenants] ([Id]) ON DELETE NO ACTION;
ALTER TABLE [BranchUsers] ADD CONSTRAINT [FK_BranchUsers_Branches_BranchId]
    FOREIGN KEY ([BranchId]) REFERENCES [Branches] ([Id]) ON DELETE NO ACTION;
ALTER TABLE [Departments] ADD CONSTRAINT [FK_Departments_Branches_BranchId]
    FOREIGN KEY ([BranchId]) REFERENCES [Branches] ([Id]) ON DELETE NO ACTION;
ALTER TABLE [TenantUsers] ADD CONSTRAINT [FK_TenantUsers_Tenants_TenantId]
    FOREIGN KEY ([TenantId]) REFERENCES [Tenants] ([Id]) ON DELETE NO ACTION;

-- 5. Drop and recreate unique indexes to handle nullable TenantId
DROP INDEX IF EXISTS [IX_Payments_TenantId_PaymentNumber] ON [Payments];
CREATE UNIQUE INDEX [IX_Payments_TenantId_PaymentNumber] ON [Payments] ([TenantId], [PaymentNumber])
    WHERE [TenantId] IS NOT NULL;

DROP INDEX IF EXISTS [IX_Patients_TenantId_PatientNumber] ON [Patients];
CREATE UNIQUE INDEX [IX_Patients_TenantId_PatientNumber] ON [Patients] ([TenantId], [PatientNumber])
    WHERE [TenantId] IS NOT NULL;

DROP INDEX IF EXISTS [IX_Invoices_TenantId_InvoiceNumber] ON [Invoices];
CREATE UNIQUE INDEX [IX_Invoices_TenantId_InvoiceNumber] ON [Invoices] ([TenantId], [InvoiceNumber])
    WHERE [TenantId] IS NOT NULL;

PRINT 'Migration completed successfully - TenantId and BranchId are now nullable';
