using ClinIQ.Domain.Enums;

namespace ClinIQ.Shared.DTOs.Patients;

public record PatientDto(
    Guid Id,
    string PatientNumber,
    string? MRN,
    string FirstName,
    string LastName,
    string? MiddleName,
    string FullName,
    DateTime? DateOfBirth,
    int? Age,
    Gender? Gender,
    BloodGroup? BloodGroup,
    string? Email,
    string? Phone,
    string? Address,
    string? City,
    string? PhotoUrl,
    bool IsActive,
    bool IsVerified,
    DateTime? LastVisitDate,
    DateTime CreatedAt
);

public record PatientDetailDto(
    Guid Id,
    string PatientNumber,
    string? MRN,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Title,
    DateTime? DateOfBirth,
    int? Age,
    Gender? Gender,
    BloodGroup? BloodGroup,
    MaritalStatus? MaritalStatus,
    string? Nationality,
    string? Religion,
    string? Occupation,
    string? PhotoUrl,
    string? Email,
    string? Phone,
    string? AlternatePhone,
    string? Address,
    string? City,
    string? State,
    string? Country,
    string? PostalCode,
    string? EmergencyContactName,
    string? EmergencyContactRelation,
    string? EmergencyContactPhone,
    IEnumerable<string>? Allergies,
    IEnumerable<string>? ChronicConditions,
    string? FamilyHistory,
    string? SurgicalHistory,
    string? SocialHistory,
    string? Notes,
    bool IsActive,
    bool IsVerified,
    DateTime? LastVisitDate,
    DateTime CreatedAt,
    DateTime? UpdatedAt
);
