namespace ClinIQ.Shared.DTOs.Inventory;

public record ItemDto(
    Guid Id,
    string Name,
    string Code,
    string? Barcode,
    string? CategoryName,
    bool IsMedicine,
    string? GenericName,
    string? BrandName,
    string? Strength,
    string? Form,
    decimal SellingPrice,
    decimal CurrentStock,
    decimal MinimumStock,
    decimal ReorderLevel,
    bool IsActive
);

public record ItemDetailDto(
    Guid Id,
    string Name,
    string Code,
    string? Barcode,
    string? Description,
    Guid? CategoryId,
    string? CategoryName,
    bool IsMedicine,
    string? GenericName,
    string? BrandName,
    Guid? ManufacturerId,
    string? ManufacturerName,
    string? Strength,
    string? Form,
    string? PackSize,
    bool RequiresPrescription,
    string? PurchaseUnit,
    string? SaleUnit,
    decimal ConversionFactor,
    decimal PurchasePrice,
    decimal SellingPrice,
    decimal? MRP,
    decimal TaxPercent,
    bool IsTaxInclusive,
    decimal CurrentStock,
    decimal MinimumStock,
    decimal MaximumStock,
    decimal ReorderLevel,
    bool TracksExpiry,
    bool TracksBatches,
    bool IsActive,
    DateTime CreatedAt,
    DateTime? UpdatedAt
);

public record CreateItemRequest(
    string Name,
    string Code,
    string? Barcode,
    string? Description,
    Guid? CategoryId,
    bool IsMedicine,
    string? GenericName,
    string? BrandName,
    Guid? ManufacturerId,
    string? Strength,
    string? Form,
    string? PackSize,
    bool RequiresPrescription,
    string? PurchaseUnit,
    string? SaleUnit,
    decimal ConversionFactor,
    decimal PurchasePrice,
    decimal SellingPrice,
    decimal? MRP,
    decimal TaxPercent,
    bool IsTaxInclusive,
    decimal MinimumStock,
    decimal MaximumStock,
    decimal ReorderLevel,
    bool TracksExpiry,
    bool TracksBatches,
    Guid? DefaultWarehouseId
);
